### ISSUE TITLE
Delete repository?

### ISSUE THREAD

**Issue by freenerd** [mapbox/osrm-frontend-v2#9]
Looks like https://github.com/Project-OSRM/osrm-frontend is the canonical source now. No need to keep this fork under the mapbox org I guess?

/cc @amyleew @batpad @geohacker @mokob

**Comment by geohacker** [comment]
@freenerd good question. If I remember right, we forked to [quickly bake in some features](https://github.com/mapbox/osrm-frontend-v2/commits/mb-pages) that we wanted for directions QA.

Going to pass this on to @srividyacb  and @oini for the decision.

**Comment by srividyacb** [comment]
@freenerd We forked this repository to mapbox.com to add following features to it which help us in QA process:
- To switch to Mapbox Directions API for routing as we were seeing some discrepancies during route calculation in [Project OSRM frontend](http://map.project-osrm.org/)
- @batpad recently made a fix which made multiple profile routing in the same frontend - walking and cycling.

cc @oini @geohacker

**Comment by geohacker** [comment]
@srividyacb can you check if those changes exist upstream?

**Comment by freenerd** [comment]
If still in use, I'm cool with keeping this fork here. You should change the readme to depcit why this fork exists though.

Also you might want to make sure your fork stays up-to-date with the upstream osrm-frontend.

**Comment by srividyacb** [comment]
All next actions [#10](https://github.com/mapbox/osrm-frontend-v2/issues/10) Closing
